appName: prod-flask-app
namespace: prod
hostname: production.my-inc.com
ingressPort: 32764
serviceAccount:
  create: false
service:
  port: 80
  type: ClusterIP  # Ensure this is included
ingress:
  enabled: false  # Include this if ingress is not needed
autoscaling:
  enabled: false
